import { MonsterData } from "./types";

export const MONSTER_LIST: MonsterData[] = [
  { name: "Aarakocra Aeromancer", slug: "aarakocra-aeromancer" },
  { name: "Aarakocra Skirmisher", slug: "aarakocra-skirmisher" },
  { name: "Aberrant Cultist", slug: "aberrant-cultist" },
  { name: "Aberrant Spirit", slug: "aberrant-spirit" },
  { name: "Aboleth", slug: "aboleth" },
  { name: "Abominable Yeti", slug: "abominable-yeti" },
  { name: "Adult Black Dragon", slug: "adult-black-dragon" },
  { name: "Adult Blue Dragon", slug: "adult-blue-dragon" },
  { name: "Adult Brass Dragon", slug: "adult-brass-dragon" },
  { name: "Adult Bronze Dragon", slug: "adult-bronze-dragon" },
  { name: "Adult Copper Dragon", slug: "adult-copper-dragon" },
  { name: "Adult Gold Dragon", slug: "adult-gold-dragon" },
  { name: "Adult Green Dragon", slug: "adult-green-dragon" },
  { name: "Adult Red Dragon", slug: "adult-red-dragon" },
  { name: "Adult Silver Dragon", slug: "adult-silver-dragon" },
  { name: "Adult White Dragon", slug: "adult-white-dragon" },
  { name: "Air Elemental", slug: "air-elemental" },
  { name: "Allosaurus", slug: "allosaurus" },
  { name: "Ancient Black Dragon", slug: "ancient-black-dragon" },
  { name: "Ancient Blue Dragon", slug: "ancient-blue-dragon" },
  { name: "Ancient Brass Dragon", slug: "ancient-brass-dragon" },
  { name: "Ancient Bronze Dragon", slug: "ancient-bronze-dragon" },
  { name: "Ancient Copper Dragon", slug: "ancient-copper-dragon" },
  { name: "Ancient Gold Dragon", slug: "ancient-gold-dragon" },
  { name: "Ancient Green Dragon", slug: "ancient-green-dragon" },
  { name: "Ancient Red Dragon", slug: "ancient-red-dragon" },
  { name: "Ancient Silver Dragon", slug: "ancient-silver-dragon" },
  { name: "Ancient White Dragon", slug: "ancient-white-dragon" },
  { name: "Animal Lord", slug: "animal-lord" },
  { name: "Animated Armor", slug: "animated-armor" },
  { name: "Animated Broom", slug: "animated-broom" },
  { name: "Animated Flying Sword", slug: "animated-flying-sword" },
  { name: "Animated Object", slug: "animated-object" },
  { name: "Animated Rug Of Smothering", slug: "animated-rug-of-smothering" },
  { name: "Ankheg", slug: "ankheg" },
  { name: "Ankylosaurus", slug: "ankylosaurus" },
  { name: "Ape", slug: "ape" },
  { name: "Arcanaloth", slug: "arcanaloth" },
  { name: "Arch Hag", slug: "arch-hag" },
  { name: "Archelon", slug: "archelon" },
  { name: "Archmage", slug: "archmage" },
  { name: "Archpriest", slug: "archpriest" },
  { name: "Assassin", slug: "assassin" },
  { name: "Awakened Shrub", slug: "awakened-shrub" },
  { name: "Awakened Tree", slug: "awakened-tree" },
  { name: "Axe Beak", slug: "axe-beak" },
  { name: "Azer Pyromancer", slug: "azer-pyromancer" },
  { name: "Azer Sentinel", slug: "azer-sentinel" },
  { name: "Baboon", slug: "baboon" },
  { name: "Badger", slug: "badger" },
  { name: "Balor", slug: "balor" },
  { name: "Bandit", slug: "bandit" },
  { name: "Bandit Captain", slug: "bandit-captain" },
  { name: "Bandit Crime Lord", slug: "bandit-crime-lord" },
  { name: "Bandit Deceiver", slug: "bandit-deceiver" },
  { name: "Banshee", slug: "banshee" },
  { name: "Barbed Devil", slug: "barbed-devil" },
  { name: "Barlgura", slug: "barlgura" },
  { name: "Basilisk", slug: "basilisk" },
  { name: "Bat", slug: "bat" },
  { name: "Bearded Devil", slug: "bearded-devil" },
  { name: "Beast Of The Land", slug: "beast-of-the-land" },
  { name: "Beast Of The Sea", slug: "beast-of-the-sea" },
  { name: "Beast Of The Sky", slug: "beast-of-the-sky" },
  { name: "Behir", slug: "behir" },
  { name: "Beholder", slug: "beholder" },
  { name: "Beholder Zombie", slug: "beholder-zombie" },
  { name: "Berserker", slug: "berserker" },
  { name: "Berserker Commander", slug: "berserker-commander" },
  { name: "Bestial Spirit", slug: "bestial-spirit" },
  { name: "Black Bear", slug: "black-bear" },
  { name: "Black Dragon Wyrmling", slug: "black-dragon-wyrmling" },
  { name: "Black Pudding", slug: "black-pudding" },
  { name: "Blink Dog", slug: "blink-dog" },
  { name: "Blob Of Annihilation", slug: "blob-of-annihilation" },
  { name: "Blood Hawk", slug: "blood-hawk" },
  { name: "Blue Dragon Wyrmling", slug: "blue-dragon-wyrmling" },
  { name: "Blue Slaad", slug: "blue-slaad" },
  { name: "Boar", slug: "boar" },
  { name: "Bone Devil", slug: "bone-devil" },
  { name: "Bone Naga", slug: "bone-naga" },
  { name: "Brass Dragon Wyrmling", slug: "brass-dragon-wyrmling" },
  { name: "Brazen Gorgon", slug: "brazen-gorgon" },
  { name: "Bronze Dragon Wyrmling", slug: "bronze-dragon-wyrmling" },
  { name: "Brown Bear", slug: "brown-bear" },
  { name: "Bugbear Stalker", slug: "bugbear-stalker" },
  { name: "Bugbear Warrior", slug: "bugbear-warrior" },
  { name: "Bulette", slug: "bulette" },
  { name: "Bulette Pup", slug: "bulette-pup" },
  { name: "Bullywug Bog Sage", slug: "bullywug-bog-sage" },
  { name: "Bullywug Warrior", slug: "bullywug-warrior" },
  { name: "Cambion", slug: "cambion" },
  { name: "Camel", slug: "camel" },
  { name: "Carrion Crawler", slug: "carrion-crawler" },
  { name: "Cat", slug: "cat" },
  { name: "Celestial Spirit", slug: "celestial-spirit" },
  { name: "Centaur Trooper", slug: "centaur-trooper" },
  { name: "Centaur Warden", slug: "centaur-warden" },
  { name: "Chain Devil", slug: "chain-devil" },
  { name: "Chasme", slug: "chasme" },
  { name: "Chimera", slug: "chimera" },
  { name: "Chuul", slug: "chuul" },
  { name: "Clay Golem", slug: "clay-golem" },
  { name: "Cloaker", slug: "cloaker" },
  { name: "Cloud Giant", slug: "cloud-giant" },
  { name: "Cockatrice", slug: "cockatrice" },
  { name: "Cockatrice Regent", slug: "cockatrice-regent" },
  { name: "Colossus", slug: "colossus" },
  { name: "Commoner", slug: "commoner" },
  { name: "Constrictor Snake", slug: "constrictor-snake" },
  { name: "Construct Spirit", slug: "construct-spirit" },
  { name: "Copper Dragon Wyrmling", slug: "copper-dragon-wyrmling" },
  { name: "Couatl", slug: "couatl" },
  { name: "Crab", slug: "crab" },
  { name: "Crawling Claw", slug: "crawling-claw" },
  { name: "Crocodile", slug: "crocodile" },
  { name: "Cultist", slug: "cultist" },
  { name: "Cultist Fanatic", slug: "cultist-fanatic" },
  { name: "Cultist Hierophant", slug: "cultist-hierophant" },
  { name: "Cultist Of Bane", slug: "cultist-of-bane" },
  { name: "Cultist Of Bhaal", slug: "cultist-of-bhaal" },
  { name: "Cultist Of Myrkul", slug: "cultist-of-myrkul" },
  { name: "Cyclops Oracle", slug: "cyclops-oracle" },
  { name: "Cyclops Sentry", slug: "cyclops-sentry" },
  { name: "Dao", slug: "dao" },
  { name: "Darkmantle", slug: "darkmantle" },
  { name: "Death Cultist", slug: "death-cultist" },
  { name: "Death Dog", slug: "death-dog" },
  { name: "Death Knight", slug: "death-knight" },
  { name: "Death Knight Aspirant", slug: "death-knight-aspirant" },
  { name: "Death Slaad", slug: "death-slaad" },
  { name: "Death Tyrant", slug: "death-tyrant" },
  { name: "Deer", slug: "deer" },
  { name: "Demilich", slug: "demilich" },
  { name: "Deva", slug: "deva" },
  { name: "Dire Wolf", slug: "dire-wolf" },
  { name: "Dire Worg", slug: "dire-worg" },
  { name: "Displacer Beast", slug: "displacer-beast" },
  { name: "Djinni", slug: "djinni" },
  { name: "Doppelganger", slug: "doppelganger" },
  { name: "Dracolich", slug: "dracolich" },
  { name: "Draconic Spirit", slug: "draconic-spirit" },
  { name: "Draft Horse", slug: "draft-horse" },
  { name: "Dragon Turtle", slug: "dragon-turtle" },
  { name: "Dretch", slug: "dretch" },
  { name: "Drider", slug: "drider" },
  { name: "Drow Elite Warrior Of Lolth", slug: "drow-elite-warrior-of-lolth" },
  { name: "Drow Mage Of Lolth", slug: "drow-mage-of-lolth" },
  { name: "Drow Of Lolth", slug: "drow-of-lolth" },
  { name: "Drow Priestess Of Lolth", slug: "drow-priestess-of-lolth" },
  { name: "Druid", slug: "druid" },
  { name: "Dryad", slug: "dryad" },
  { name: "Dust Mephit", slug: "dust-mephit" },
  { name: "Eagle", slug: "eagle" },
  { name: "Earth Elemental", slug: "earth-elemental" },
  { name: "Efreeti", slug: "efreeti" },
  { name: "Elemental Cataclysm", slug: "elemental-cataclysm" },
  { name: "Elemental Cultist", slug: "elemental-cultist" },
  { name: "Elemental Spirit", slug: "elemental-spirit" },
  { name: "Elephant", slug: "elephant" },
  { name: "Elk", slug: "elk" },
  { name: "Empyrean", slug: "empyrean" },
  { name: "Empyrean Iota", slug: "empyrean-iota" },
  { name: "Erinyes", slug: "erinyes" },
  { name: "Ettercap", slug: "ettercap" },
  { name: "Ettin", slug: "ettin" },
  { name: "Faerie Dragon Adult", slug: "faerie-dragon-adult" },
  { name: "Faerie Dragon Youth", slug: "faerie-dragon-youth" },
  { name: "Fey Spirit", slug: "fey-spirit" },
  { name: "Fiend Cultist", slug: "fiend-cultist" },
  { name: "Fiendish Spirit", slug: "fiendish-spirit" },
  { name: "Fire Elemental", slug: "fire-elemental" },
  { name: "Fire Giant", slug: "fire-giant" },
  { name: "Flameskull", slug: "flameskull" },
  { name: "Flaming Skeleton", slug: "flaming-skeleton" },
  { name: "Flesh Golem", slug: "flesh-golem" },
  { name: "Flumph", slug: "flumph" },
  { name: "Flying Snake", slug: "flying-snake" },
  { name: "Fomorian", slug: "fomorian" },
  { name: "Frog", slug: "frog" },
  { name: "Frost Giant", slug: "frost-giant" },
  { name: "Galeb Duhr", slug: "galeb-duhr" },
  { name: "Gargoyle", slug: "gargoyle" },
  { name: "Gas Spore Fungus", slug: "gas-spore-fungus" },
  { name: "Gelatinous Cube", slug: "gelatinous-cube" },
  { name: "Ghast", slug: "ghast" },
  { name: "Ghast Gravecaller", slug: "ghast-gravecaller" },
  { name: "Ghost", slug: "ghost" },
  { name: "Ghoul", slug: "ghoul" },
  { name: "Giant Ape", slug: "giant-ape" },
  { name: "Giant Axe Beak", slug: "giant-axe-beak" },
  { name: "Giant Badger", slug: "giant-badger" },
  { name: "Giant Bat", slug: "giant-bat" },
  { name: "Giant Boar", slug: "giant-boar" },
  { name: "Giant Centipede", slug: "giant-centipede" },
  { name: "Giant Constrictor Snake", slug: "giant-constrictor-snake" },
  { name: "Giant Crab", slug: "giant-crab" },
  { name: "Giant Crocodile", slug: "giant-crocodile" },
  { name: "Giant Eagle", slug: "giant-eagle" },
  { name: "Giant Elk", slug: "giant-elk" },
  { name: "Giant Fire Beetle", slug: "giant-fire-beetle" },
  { name: "Giant Frog", slug: "giant-frog" },
  { name: "Giant Goat", slug: "giant-goat" },
  { name: "Giant Hyena", slug: "giant-hyena" },
  { name: "Giant Insect", slug: "giant-insect" },
  { name: "Giant Lizard", slug: "giant-lizard" },
  { name: "Giant Octopus", slug: "giant-octopus" },
  { name: "Giant Owl", slug: "giant-owl" },
  { name: "Giant Rat", slug: "giant-rat" },
  { name: "Giant Scorpion", slug: "giant-scorpion" },
  { name: "Giant Seahorse", slug: "giant-seahorse" },
  { name: "Giant Shark", slug: "giant-shark" },
  { name: "Giant Spider", slug: "giant-spider" },
  { name: "Giant Squid", slug: "giant-squid" },
  { name: "Giant Toad", slug: "giant-toad" },
  { name: "Giant Venomous Snake", slug: "giant-venomous-snake" },
  { name: "Giant Vulture", slug: "giant-vulture" },
  { name: "Giant Wasp", slug: "giant-wasp" },
  { name: "Giant Weasel", slug: "giant-weasel" },
  { name: "Giant Wolf Spider", slug: "giant-wolf-spider" },
  { name: "Gibbering Mouther", slug: "gibbering-mouther" },
  { name: "Githyanki Dracomancer", slug: "githyanki-dracomancer" },
  { name: "Githyanki Knight", slug: "githyanki-knight" },
  { name: "Githyanki Warrior", slug: "githyanki-warrior" },
  { name: "Githzerai Monk", slug: "githzerai-monk" },
  { name: "Githzerai Psion", slug: "githzerai-psion" },
  { name: "Githzerai Zerth", slug: "githzerai-zerth" },
  { name: "Glabrezu", slug: "glabrezu" },
  { name: "Gladiator", slug: "gladiator" },
  { name: "Gnoll Demoniac", slug: "gnoll-demoniac" },
  { name: "Gnoll Fang Of Yeenoghu", slug: "gnoll-fang-of-yeenoghu" },
  { name: "Gnoll Pack Lord", slug: "gnoll-pack-lord" },
  { name: "Gnoll Warrior", slug: "gnoll-warrior" },
  { name: "Goat", slug: "goat" },
  { name: "Goblin Boss", slug: "goblin-boss" },
  { name: "Goblin Hexer", slug: "goblin-hexer" },
  { name: "Goblin Minion", slug: "goblin-minion" },
  { name: "Goblin Warrior", slug: "goblin-warrior" },
  { name: "Gold Dragon Wyrmling", slug: "gold-dragon-wyrmling" },
  { name: "Gorgon", slug: "gorgon" },
  { name: "Goristro", slug: "goristro" },
  { name: "Graveyard Revenant", slug: "graveyard-revenant" },
  { name: "Gray Ooze", slug: "gray-ooze" },
  { name: "Gray Slaad", slug: "gray-slaad" },
  { name: "Green Dragon Wyrmling", slug: "green-dragon-wyrmling" },
  { name: "Green Hag", slug: "green-hag" },
  { name: "Green Slaad", slug: "green-slaad" },
  { name: "Grell", slug: "grell" },
  { name: "Grick", slug: "grick" },
  { name: "Grick Ancient", slug: "grick-ancient" },
  { name: "Griffon", slug: "griffon" },
  { name: "Grimlock", slug: "grimlock" },
  { name: "Guard", slug: "guard" },
  { name: "Guard Captain", slug: "guard-captain" },
  { name: "Guardian Naga", slug: "guardian-naga" },
  { name: "Gulthias Blight", slug: "gulthias-blight" },
  { name: "Half Dragon", slug: "half-dragon" },
  { name: "Harpy", slug: "harpy" },
  { name: "Haunting Revenant", slug: "haunting-revenant" },
  { name: "Hawk", slug: "hawk" },
  { name: "Hell Hound", slug: "hell-hound" },
  { name: "Helmed Horror", slug: "helmed-horror" },
  { name: "Hezrou", slug: "hezrou" },
  { name: "Hill Giant", slug: "hill-giant" },
  { name: "Hippogriff", slug: "hippogriff" },
  { name: "Hippopotamus", slug: "hippopotamus" },
  { name: "Hobgoblin Captain", slug: "hobgoblin-captain" },
  { name: "Hobgoblin Warlord", slug: "hobgoblin-warlord" },
  { name: "Hobgoblin Warrior", slug: "hobgoblin-warrior" },
  { name: "Homunculus", slug: "homunculus" },
  { name: "Hook Horror", slug: "hook-horror" },
  { name: "Horned Devil", slug: "horned-devil" },
  { name: "Hunter Shark", slug: "hunter-shark" },
  { name: "Hydra", slug: "hydra" },
  { name: "Hyena", slug: "hyena" },
  { name: "Ice Devil", slug: "ice-devil" },
  { name: "Ice Mephit", slug: "ice-mephit" },
  { name: "Imp", slug: "imp" },
  { name: "Incubus", slug: "incubus" },
  { name: "Intellect Devourer", slug: "intellect-devourer" },
  { name: "Invisible Stalker", slug: "invisible-stalker" },
  { name: "Iron Golem", slug: "iron-golem" },
  { name: "Jackal", slug: "jackal" },
  { name: "Jackalwere", slug: "jackalwere" },
  { name: "Juvenile Shadow Dragon", slug: "juvenile-shadow-dragon" },
  { name: "Kenku", slug: "kenku" },
  { name: "Killer Whale", slug: "killer-whale" },
  { name: "Knight", slug: "knight" },
  { name: "Kobold Warrior", slug: "kobold-warrior" },
  { name: "Kraken", slug: "kraken" },
  { name: "Kuo Toa", slug: "kuo-toa" },
  { name: "Kuo Toa Archpriest", slug: "kuo-toa-archpriest" },
  { name: "Kuo Toa Monitor", slug: "kuo-toa-monitor" },
  { name: "Kuo Toa Whip", slug: "kuo-toa-whip" },
  { name: "Lacedon Ghoul", slug: "lacedon-ghoul" },
  { name: "Lamia", slug: "lamia" },
  { name: "Larva", slug: "larva" },
  { name: "Lemure", slug: "lemure" },
  { name: "Lich", slug: "lich" },
  { name: "Lion", slug: "lion" },
  { name: "Lizard", slug: "lizard" },
  { name: "Lizardfolk Geomancer", slug: "lizardfolk-geomancer" },
  { name: "Lizardfolk Sovereign", slug: "lizardfolk-sovereign" },
  { name: "Mage", slug: "mage" },
  { name: "Mage Apprentice", slug: "mage-apprentice" },
  { name: "Magma Mephit", slug: "magma-mephit" },
  { name: "Magmin", slug: "magmin" },
  { name: "Mammoth", slug: "mammoth" },
  { name: "Manes", slug: "manes" },
  { name: "Manes Vaporspawn", slug: "manes-vaporspawn" },
  { name: "Manticore", slug: "manticore" },
  { name: "Marid", slug: "marid" },
  { name: "Marilith", slug: "marilith" },
  { name: "Mastiff", slug: "mastiff" },
  { name: "Medusa", slug: "medusa" },
  { name: "Merfolk Skirmisher", slug: "merfolk-skirmisher" },
  { name: "Merfolk Wavebender", slug: "merfolk-wavebender" },
  { name: "Merrow", slug: "merrow" },
  { name: "Mezzoloth", slug: "mezzoloth" },
  { name: "Mimic", slug: "mimic" },
  { name: "Mind Flayer", slug: "mind-flayer" },
  { name: "Mind Flayer Arcanist", slug: "mind-flayer-arcanist" },
  { name: "Minotaur Of Baphomet", slug: "minotaur-of-baphomet" },
  { name: "Minotaur Skeleton", slug: "minotaur-skeleton" },
  { name: "Mud Mephit", slug: "mud-mephit" },
  { name: "Mule", slug: "mule" },
  { name: "Mummy", slug: "mummy" },
  { name: "Mummy Lord", slug: "mummy-lord" },
  { name: "Myconid Adult", slug: "myconid-adult" },
  { name: "Myconid Sovereign", slug: "myconid-sovereign" },
  { name: "Myconid Spore Servant", slug: "myconid-spore-servant" },
  { name: "Myconid Sprout", slug: "myconid-sprout" },
  { name: "Nalfeshnee", slug: "nalfeshnee" },
  { name: "Needle Blight", slug: "needle-blight" },
  { name: "Night Hag", slug: "night-hag" },
  { name: "Nightmare", slug: "nightmare" },
  { name: "Noble", slug: "noble" },
  { name: "Noble Prodigy", slug: "noble-prodigy" },
  { name: "Nothic", slug: "nothic" },
  { name: "Nycaloth", slug: "nycaloth" },
  { name: "Ochre Jelly", slug: "ochre-jelly" },
  { name: "Octopus", slug: "octopus" },
  { name: "Ogre", slug: "ogre" },
  { name: "Ogre Zombie", slug: "ogre-zombie" },
  { name: "Ogrillon Ogre", slug: "ogrillon-ogre" },
  { name: "Oni", slug: "oni" },
  { name: "Otherworldly Steed", slug: "otherworldly-steed" },
  { name: "Otyugh", slug: "otyugh" },
  { name: "Owl", slug: "owl" },
  { name: "Owlbear", slug: "owlbear" },
  { name: "Panther", slug: "panther" },
  { name: "Pegasus", slug: "pegasus" },
  { name: "Performer", slug: "performer" },
  { name: "Performer Legend", slug: "performer-legend" },
  { name: "Performer Maestro", slug: "performer-maestro" },
  { name: "Peryton", slug: "peryton" },
  { name: "Phase Spider", slug: "phase-spider" },
  { name: "Piercer", slug: "piercer" },
  { name: "Piranha", slug: "piranha" },
  { name: "Pirate", slug: "pirate" },
  { name: "Pirate Admiral", slug: "pirate-admiral" },
  { name: "Pirate Captain", slug: "pirate-captain" },
  { name: "Pit Fiend", slug: "pit-fiend" },
  { name: "Pixie", slug: "pixie" },
  { name: "Pixie Wonderbringer", slug: "pixie-wonderbringer" },
  { name: "Planetar", slug: "planetar" },
  { name: "Plesiosaurus", slug: "plesiosaurus" },
  { name: "Polar Bear", slug: "polar-bear" },
  { name: "Poltergeist", slug: "poltergeist" },
  { name: "Pony", slug: "pony" },
  { name: "Priest", slug: "priest" },
  { name: "Priest Acolyte", slug: "priest-acolyte" },
  { name: "Primeval Owlbear", slug: "primeval-owlbear" },
  { name: "Pseudodragon", slug: "pseudodragon" },
  { name: "Psychic Gray Ooze", slug: "psychic-gray-ooze" },
  { name: "Pteranodon", slug: "pteranodon" },
  { name: "Purple Worm", slug: "purple-worm" },
  { name: "Quaggoth", slug: "quaggoth" },
  { name: "Quaggoth Thonot", slug: "quaggoth-thonot" },
  { name: "Quasit", slug: "quasit" },
  { name: "Questing Knight", slug: "questing-knight" },
  { name: "Rakshasa", slug: "rakshasa" },
  { name: "Rat", slug: "rat" },
  { name: "Raven", slug: "raven" },
  { name: "Red Dragon Wyrmling", slug: "red-dragon-wyrmling" },
  { name: "Red Slaad", slug: "red-slaad" },
  { name: "Reef Shark", slug: "reef-shark" },
  { name: "Remorhaz", slug: "remorhaz" },
  { name: "Revenant", slug: "revenant" },
  { name: "Rhinoceros", slug: "rhinoceros" },
  { name: "Riding Horse", slug: "riding-horse" },
  { name: "Roc", slug: "roc" },
  { name: "Roper", slug: "roper" },
  { name: "Rust Monster", slug: "rust-monster" },
  { name: "Saber Toothed Tiger", slug: "saber-toothed-tiger" },
  { name: "Sahuagin Baron", slug: "sahuagin-baron" },
  { name: "Sahuagin Priest", slug: "sahuagin-priest" },
  { name: "Sahuagin Warrior", slug: "sahuagin-warrior" },
  { name: "Salamander", slug: "salamander" },
  { name: "Salamander Fire Snake", slug: "salamander-fire-snake" },
  { name: "Salamander Inferno Master", slug: "salamander-inferno-master" },
  { name: "Satyr", slug: "satyr" },
  { name: "Satyr Revelmaster", slug: "satyr-revelmaster" },
  { name: "Scarecrow", slug: "scarecrow" },
  { name: "Scorpion", slug: "scorpion" },
  { name: "Scout", slug: "scout" },
  { name: "Scout Captain", slug: "scout-captain" },
  { name: "Sea Hag", slug: "sea-hag" },
  { name: "Seahorse", slug: "seahorse" },
  { name: "Shadow", slug: "shadow" },
  { name: "Shadow Demon", slug: "shadow-demon" },
  { name: "Shadow Dragon", slug: "shadow-dragon" },
  { name: "Shambling Mound", slug: "shambling-mound" },
  { name: "Shield Guardian", slug: "shield-guardian" },
  { name: "Shrieker Fungus", slug: "shrieker-fungus" },
  { name: "Silver Dragon Wyrmling", slug: "silver-dragon-wyrmling" },
  { name: "Skeleton", slug: "skeleton" },
  { name: "Slaad Tadpole", slug: "slaad-tadpole" },
  { name: "Smoke Mephit", slug: "smoke-mephit" },
  { name: "Solar", slug: "solar" },
  { name: "Spectator", slug: "spectator" },
  { name: "Specter", slug: "specter" },
  { name: "Sphinx Of Lore", slug: "sphinx-of-lore" },
  { name: "Sphinx Of Secrets", slug: "sphinx-of-secrets" },
  { name: "Sphinx Of Valor", slug: "sphinx-of-valor" },
  { name: "Sphinx Of Wonder", slug: "sphinx-of-wonder" },
  { name: "Spider", slug: "spider" },
  { name: "Spined Devil", slug: "spined-devil" },
  { name: "Spirit Naga", slug: "spirit-naga" },
  { name: "Sprite", slug: "sprite" },
  { name: "Spy", slug: "spy" },
  { name: "Spy Master", slug: "spy-master" },
  { name: "Steam Mephit", slug: "steam-mephit" },
  { name: "Stirge", slug: "stirge" },
  { name: "Stone Giant", slug: "stone-giant" },
  { name: "Stone Golem", slug: "stone-golem" },
  { name: "Storm Giant", slug: "storm-giant" },
  { name: "Succubus", slug: "succubus" },
  { name: "Swarm Of Bats", slug: "swarm-of-bats" },
  { name: "Swarm Of Crawling Claws", slug: "swarm-of-crawling-claws" },
  { name: "Swarm Of Dretches", slug: "swarm-of-dretches" },
  { name: "Swarm Of Insects", slug: "swarm-of-insects" },
  { name: "Swarm Of Larvae", slug: "swarm-of-larvae" },
  { name: "Swarm Of Lemures", slug: "swarm-of-lemures" },
  { name: "Swarm Of Piranhas", slug: "swarm-of-piranhas" },
  { name: "Swarm Of Rats", slug: "swarm-of-rats" },
  { name: "Swarm Of Ravens", slug: "swarm-of-ravens" },
  { name: "Swarm Of Stirges", slug: "swarm-of-stirges" },
  { name: "Swarm Of Venomous Snakes", slug: "swarm-of-venomous-snakes" },
  { name: "Tarrasque", slug: "tarrasque" },
  { name: "Thri Kreen Marauder", slug: "thri-kreen-marauder" },
  { name: "Thri Kreen Psion", slug: "thri-kreen-psion" },
  { name: "Tiger", slug: "tiger" },
  { name: "Tough", slug: "tough" },
  { name: "Tough Boss", slug: "tough-boss" },
  { name: "Treant", slug: "treant" },
  { name: "Tree Blight", slug: "tree-blight" },
  { name: "Triceratops", slug: "triceratops" },
  { name: "Troglodyte", slug: "troglodyte" },
  { name: "Troll", slug: "troll" },
  { name: "Troll Limb", slug: "troll-limb" },
  { name: "Twig Blight", slug: "twig-blight" },
  { name: "Tyrannosaurus Rex", slug: "tyrannosaurus-rex" },
  { name: "Ultroloth", slug: "ultroloth" },
  { name: "Umber Hulk", slug: "umber-hulk" },
  { name: "Undead Spirit", slug: "undead-spirit" },
  { name: "Unicorn", slug: "unicorn" },
  { name: "Vampire", slug: "vampire" },
  { name: "Vampire Familiar", slug: "vampire-familiar" },
  { name: "Vampire Nightbringer", slug: "vampire-nightbringer" },
  { name: "Vampire Spawn", slug: "vampire-spawn" },
  { name: "Vampire Umbral Lord", slug: "vampire-umbral-lord" },
  { name: "Venomous Snake", slug: "venomous-snake" },
  { name: "Vine Blight", slug: "vine-blight" },
  { name: "Violet Fungus", slug: "violet-fungus" },
  { name: "Violet Fungus Necrohulk", slug: "violet-fungus-necrohulk" },
  { name: "Vrock", slug: "vrock" },
  { name: "Vulture", slug: "vulture" },
  { name: "Warhorse", slug: "warhorse" },
  { name: "Warhorse Skeleton", slug: "warhorse-skeleton" },
  { name: "Warrior Commander", slug: "warrior-commander" },
  { name: "Warrior Infantry", slug: "warrior-infantry" },
  { name: "Warrior Veteran", slug: "warrior-veteran" },
  { name: "Water Elemental", slug: "water-elemental" },
  { name: "Water Weird", slug: "water-weird" },
  { name: "Weasel", slug: "weasel" },
  { name: "Werebear", slug: "werebear" },
  { name: "Wereboar", slug: "wereboar" },
  { name: "Wererat", slug: "wererat" },
  { name: "Weretiger", slug: "weretiger" },
  { name: "Werewolf", slug: "werewolf" },
  { name: "White Dragon Wyrmling", slug: "white-dragon-wyrmling" },
  { name: "Wight", slug: "wight" },
  { name: "Will O Wisp", slug: "will-o--wisp" },
  { name: "Winged Kobold", slug: "winged-kobold" },
  { name: "Winter Wolf", slug: "winter-wolf" },
  { name: "Wolf", slug: "wolf" },
  { name: "Worg", slug: "worg" },
  { name: "Wraith", slug: "wraith" },
  { name: "Wyvern", slug: "wyvern" },
  { name: "Xorn", slug: "xorn" },
  { name: "Yeti", slug: "yeti" },
  { name: "Yochlol", slug: "yochlol" },
  { name: "Young Black Dragon", slug: "young-black-dragon" },
  { name: "Young Blue Dragon", slug: "young-blue-dragon" },
  { name: "Young Brass Dragon", slug: "young-brass-dragon" },
  { name: "Young Bronze Dragon", slug: "young-bronze-dragon" },
  { name: "Young Copper Dragon", slug: "young-copper-dragon" },
  { name: "Young Gold Dragon", slug: "young-gold-dragon" },
  { name: "Young Green Dragon", slug: "young-green-dragon" },
  { name: "Young Red Dragon", slug: "young-red-dragon" },
  { name: "Young Remorhaz", slug: "young-remorhaz" },
  { name: "Young Silver Dragon", slug: "young-silver-dragon" },
  { name: "Young White Dragon", slug: "young-white-dragon" },
  { name: "Yuan Ti Abomination", slug: "yuan-ti-abomination" },
  { name: "Yuan Ti Infiltrator", slug: "yuan-ti-infiltrator" },
  { name: "Yuan Ti Malison (Type 1)", slug: "yuan-ti-malison-type-1" },
  { name: "Yuan Ti Malison (Type 2)", slug: "yuan-ti-malison-type-2" },
  { name: "Yuan Ti Malison (Type 3)", slug: "yuan-ti-malison-type-3" },
  { name: "Zombie", slug: "zombie" },
];
